### PR TITLE
Add feature that can (re)-start the DNS and proxy container

### PR DESCRIPTION
**Pull request by TLyngeJ**
This feature will give the user the capability of starting the DNS and proxy container in case those got stopped for one reason or another.

### CODE REVIEW

**Comment by lmakarov** [comment]
Thanks for the PR!

We may be adding more service containers soon (e.g. an ssh-agent container), so this needs to be unified (e.g. `dsh reset-system-services` /  `dsh rss`)

Also, similar pieces exist in the Vagrantfile (Mac and Win) and will need to be synchronized with what is done in dsh for Linux-only:
- https://github.com/blinkreaction/boot2docker-vagrant/blob/develop/Vagrantfile#L310-L315
- https://github.com/blinkreaction/boot2docker-vagrant/blob/develop/Vagrantfile#L326-L330

**Comment by TLyngeJ** [comment]
Consider this more as a proposition to solve an issue I've had several times, when bulk removing containers. I know it's not an issue everyone is having on a daily basis.

Feel free to scrap this if you are already cooking up something similar.

I am looking forward to it :-)

**Comment by achekulaev** [comment]
https://github.com/blinkreaction/drude/commit/e6980c1c7850829e6da8e9bd1c3f00ba2bdb4362

**Comment by achekulaev** [comment]
@TLyngeJ thanks for good idea

**Pull request closed without merging**
