### PR TITLE
issue-141: check if projects folder isn't under .babun folder

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by achekulaev** [comment]
I think this should be inside `up` function

**Comment by lmakarov** [comment]
@achekulaev the only time Vagrantfile would be placed anywhere is when `dsh install boot2docker` runs.
I agree there is a chance that user would move things manually, but that's something we won't be able to handle well anyway.
While this is a small check anyway, I think I logically belongs to the `install` use case, rather then the `up` one.

**Comment by achekulaev** [comment]
I still don't like it. It's better to fix boot2docker-vagrant. 
It's not that hard to make it to work anywhere. We just need to transform path ourselves in Vagrantfile instead of using cygpath there.
`cygpath -aw #{vagrant_root} | tr -d : | tr \\\\ /` already does almost what's needed. Just replace drive letter with lowercase and add `/` at the beginning and you're done.

So instead of creating mere workaround we could fix the problem itself.

**Comment by lmakarov** [comment]
This should be covered in the docs - don't put the projects folder anywhere in babun's home directory.

**Pull request closed without merging**
