### PR TITLE
Ssh-add: return correct status of command instead of 1.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lmakarov** [comment]
LGTM
ping @achekulaev

**Comment by achekulaev** [comment]
@vgrygoryev 
Please also change this
https://github.com/blinkreaction/drude/pull/143/files#diff-0d4f4194cf78e224ed1fd8aa10d0beaeR825
to `return 1`

**Comment by achekulaev** [comment]
@vgrygoryev also you can not just remove exits as function **needs** to exit at those points. You should use `return $?`

**Comment by ghost** [comment]
@achekulaev Thank you. I add return $? instead of exit 1, and replace exit with return

**Comment by achekulaev** [comment]
LGTM

**Pull request merged**
